"""Seed content for Dr Dukaan. All fictional entries are labelled as demo."""

SERVICES = [
    {
        "name": "Website Development",
        "slug": "website-development",
        "icon": "Globe",
        "headline": "Your Business Deserves More Than a Basic Website.",
        "short_description": "Fast, modern, conversion-focused websites that turn visitors into enquiries and customers.",
        "long_description": "We build fast, modern and conversion-focused websites designed to turn visitors into enquiries and customers. Your website loads fast, looks premium on every phone, and gives customers an easy way to contact you.",
        "benefits": ["Professional online presence", "Mobile-first experience", "WhatsApp integration", "Lead forms", "SEO-ready architecture", "Analytics", "Conversion-focused design"],
        "cta": "Build My Website",
        "featured": True,
        "order": 1,
        "seo_title": "Website Development for Local Businesses | Dr Dukaan",
        "seo_description": "Fast, mobile-first, conversion-focused websites for local businesses in Hyderabad, Kurnool and across India.",
    },
    {
        "name": "Mobile App Development",
        "slug": "mobile-app-development",
        "icon": "Smartphone",
        "headline": "Keep Your Customers Connected to Your Business.",
        "short_description": "Custom mobile apps for bookings, orders, memberships and repeat business.",
        "long_description": "Custom mobile apps that help businesses improve customer engagement, bookings, orders, memberships and repeat business.",
        "benefits": ["Android & iOS", "Customer accounts", "Bookings", "Notifications", "Orders", "Memberships", "Business-specific features"],
        "cta": "Build My App",
        "featured": False,
        "order": 2,
        "seo_title": "Mobile App Development | Dr Dukaan",
        "seo_description": "Custom Android and iOS apps for local businesses — bookings, orders, memberships and customer engagement.",
    },
    {
        "name": "E-Commerce Development",
        "slug": "ecommerce-development",
        "icon": "ShoppingCart",
        "headline": "Turn Your Products Into an Online Store.",
        "short_description": "Launch an online store so customers can discover and buy beyond your physical location.",
        "long_description": "Launch an online store that allows your customers to discover, enquire and purchase your products beyond your physical location.",
        "benefits": ["Product catalogue", "Online payments architecture", "Order management", "WhatsApp integration", "Customer accounts", "Analytics", "Mobile-first shopping"],
        "cta": "Launch My Store",
        "featured": True,
        "order": 3,
        "seo_title": "E-Commerce Development | Dr Dukaan",
        "seo_description": "Online stores for local retailers and wholesalers — catalogue, orders, payments and WhatsApp selling.",
    },
    {
        "name": "Digital Marketing",
        "slug": "digital-marketing",
        "icon": "TrendingUp",
        "headline": "Get Your Business in Front of the Right Customers.",
        "short_description": "Growth strategies built around your business, location, customers and goals.",
        "long_description": "We create digital growth strategies designed around your business, location, customers and goals — focused on enquiries and sales, not vanity metrics.",
        "benefits": ["Growth strategy", "Lead generation", "Search visibility", "Campaign optimization", "Conversion tracking", "Performance reporting"],
        "cta": "Grow My Business",
        "featured": True,
        "order": 4,
        "seo_title": "Digital Marketing for Local Businesses | Dr Dukaan",
        "seo_description": "Digital growth strategies for local businesses — lead generation, visibility and measurable results.",
    },
    {
        "name": "Google Ads",
        "slug": "google-ads",
        "icon": "Target",
        "headline": "Show Up When Customers Are Searching.",
        "short_description": "Reach people actively searching for your products or services on Google.",
        "long_description": "Reach people actively searching for your products or services through targeted Google advertising campaigns with proper conversion tracking.",
        "benefits": ["Search campaigns", "Local campaigns", "Conversion tracking", "Keyword strategy", "Landing pages", "Performance optimization"],
        "cta": "Run Google Ads",
        "featured": False,
        "order": 5,
        "seo_title": "Google Ads Management | Dr Dukaan",
        "seo_description": "Targeted Google Ads campaigns for local businesses with full conversion tracking.",
    },
    {
        "name": "Meta Ads",
        "slug": "meta-ads",
        "icon": "Megaphone",
        "headline": "Turn Attention Into Customers.",
        "short_description": "Targeted Facebook and Instagram campaigns focused on leads, enquiries and sales.",
        "long_description": "Reach relevant audiences across Facebook and Instagram using targeted campaigns focused on leads, enquiries and sales.",
        "benefits": ["Audience targeting", "Lead campaigns", "Remarketing architecture", "Creative testing", "Conversion tracking", "Campaign optimization"],
        "cta": "Run Meta Ads",
        "featured": False,
        "order": 6,
        "seo_title": "Meta Ads Management | Dr Dukaan",
        "seo_description": "Facebook and Instagram ad campaigns that turn attention into enquiries and sales.",
    },
    {
        "name": "SEO & Local SEO",
        "slug": "seo-local-seo",
        "icon": "Search",
        "headline": "Be Found When Customers Search for You.",
        "short_description": "Help more local customers discover your business when they search online.",
        "long_description": "Improve your search visibility and help more local customers discover your business through technical SEO, local SEO and Google Business optimization.",
        "benefits": ["Technical SEO", "On-page SEO", "Local SEO", "Keyword strategy", "Google Business optimization", "Content architecture", "Performance tracking"],
        "cta": "Improve My Visibility",
        "featured": True,
        "order": 7,
        "seo_title": "SEO & Local SEO Services | Dr Dukaan",
        "seo_description": "Get found on Google. Technical SEO, local SEO and Google Business optimization for local businesses.",
    },
    {
        "name": "Branding & Creative",
        "slug": "branding-creative",
        "icon": "Palette",
        "headline": "Make Your Business Look as Good Online as It Is Offline.",
        "short_description": "A consistent digital identity that builds trust and makes your business memorable.",
        "long_description": "Create a consistent digital identity that builds trust and makes your business memorable across your website, ads and marketing materials.",
        "benefits": ["Logo", "Brand identity", "Creative design", "Ad creatives", "Website visuals", "Marketing materials"],
        "cta": "Build My Brand",
        "featured": False,
        "order": 8,
        "seo_title": "Branding & Creative Design | Dr Dukaan",
        "seo_description": "Logos, brand identity and ad creatives that make local businesses look premium online.",
    },
    {
        "name": "Analytics & Reporting",
        "slug": "analytics-reporting",
        "icon": "BarChart3",
        "headline": "Know What Is Actually Growing Your Business.",
        "short_description": "Track your digital performance with clear data instead of guessing.",
        "long_description": "Track your digital performance with clear data instead of guessing. Know where your enquiries come from and what is actually working.",
        "benefits": ["GA4 setup", "Conversion tracking", "Traffic analysis", "Lead tracking", "Campaign performance", "Monthly reporting", "Growth recommendations"],
        "cta": "Track My Growth",
        "featured": False,
        "order": 9,
        "seo_title": "Analytics & Reporting | Dr Dukaan",
        "seo_description": "GA4 setup, conversion tracking and monthly growth reports for local businesses.",
    },
]

INDUSTRIES = [
    {
        "name": "Gyms & Fitness", "slug": "gyms-fitness", "icon": "Dumbbell",
        "description": "Digital growth systems for gyms, fitness studios and trainers.",
        "problem": "People search for gyms online but cannot easily understand memberships, facilities or how to contact the gym.",
        "solutions": ["Conversion-focused website", "Membership enquiry system", "WhatsApp integration", "Google Business visibility", "Google Ads for trial signups", "Analytics & lead tracking"],
        "recommended_services": ["Website Development", "Google Ads", "SEO & Local SEO", "Analytics & Reporting"],
        "benefits": ["More membership enquiries", "More trial visits", "More memberships"],
        "order": 1,
    },
    {
        "name": "Hospitals & Clinics", "slug": "hospitals-clinics", "icon": "Stethoscope",
        "description": "Digital presence and patient enquiry systems for hospitals, clinics and doctors.",
        "problem": "Patients search for doctors and treatments online, but many clinics have weak websites and no easy way to book or enquire.",
        "solutions": ["Professional website", "Doctor profiles", "Appointment enquiry system", "WhatsApp for patient queries", "Local SEO & Google Business", "Analytics & call tracking"],
        "recommended_services": ["Website Development", "SEO & Local SEO", "Analytics & Reporting"],
        "benefits": ["More appointment enquiries", "Better patient trust", "Higher local visibility"],
        "order": 2,
    },
    {
        "name": "Retail Stores", "slug": "retail-stores", "icon": "Store",
        "description": "Websites, catalogues and online stores for retail businesses.",
        "problem": "Customers discover products online but the store has no catalogue, no online presence and loses sales to competitors who do.",
        "solutions": ["Website with product catalogue", "E-commerce store", "WhatsApp ordering", "Google visibility", "Google & Meta Ads", "Analytics"],
        "recommended_services": ["E-Commerce Development", "Website Development", "Google Ads", "Meta Ads"],
        "benefits": ["Sales beyond footfall", "Wider customer reach", "Trackable online orders"],
        "order": 3,
    },
    {
        "name": "Wholesale Businesses", "slug": "wholesale-businesses", "icon": "Boxes",
        "description": "B2B catalogues and lead generation for wholesalers and distributors.",
        "problem": "Retail buyers cannot see the product range or prices online, so enquiries depend entirely on phone calls and word of mouth.",
        "solutions": ["Product catalogue website", "B2B enquiry system", "Lead capture forms", "WhatsApp for bulk orders", "SEO for product searches", "Digital advertising"],
        "recommended_services": ["Website Development", "E-Commerce Development", "SEO & Local SEO"],
        "benefits": ["More B2B enquiries", "New buyer relationships", "Less dependence on referrals"],
        "order": 4,
    },
    {
        "name": "Restaurants", "slug": "restaurants", "icon": "UtensilsCrossed",
        "description": "Websites, menus and local visibility for restaurants, cafes and bakeries.",
        "problem": "Diners check menus, photos and reviews online before visiting — restaurants without a strong presence lose walk-ins and orders.",
        "solutions": ["Website with menu & gallery", "Google Business optimization", "WhatsApp table bookings & orders", "Local SEO", "Meta Ads for offers", "Analytics"],
        "recommended_services": ["Website Development", "SEO & Local SEO", "Meta Ads"],
        "benefits": ["More table bookings", "More direct orders", "Stronger local discovery"],
        "order": 5,
    },
    {
        "name": "Education", "slug": "education", "icon": "GraduationCap",
        "description": "Admission enquiry systems for schools, coaching centres and institutes.",
        "problem": "Parents and students compare institutes online, but many institutions have outdated websites and no structured enquiry process.",
        "solutions": ["Modern institute website", "Course & batch pages", "Admission enquiry forms", "WhatsApp counselling", "Google Ads during admission season", "Analytics"],
        "recommended_services": ["Website Development", "Google Ads", "SEO & Local SEO"],
        "benefits": ["More admission enquiries", "Better parent trust", "Higher season conversions"],
        "order": 6,
    },
    {
        "name": "Salons & Spas", "slug": "salons", "icon": "Scissors",
        "description": "Booking and discovery systems for salons, spas and beauty businesses.",
        "problem": "Customers discover salons on Instagram and Google, but there is no easy way to see services, prices or book an appointment.",
        "solutions": ["Service & price menu website", "WhatsApp booking", "Google Business visibility", "Meta Ads for offers", "Review & trust building", "Analytics"],
        "recommended_services": ["Website Development", "Meta Ads", "SEO & Local SEO"],
        "benefits": ["More bookings", "Repeat customers", "Better local discovery"],
        "order": 7,
    },
    {
        "name": "Real Estate", "slug": "real-estate", "icon": "Building2",
        "description": "Lead generation systems for builders, developers and property consultants.",
        "problem": "Property buyers research online first, but projects without landing pages and ads lose serious buyers to competitors.",
        "solutions": ["Project landing pages", "Lead capture & site visit forms", "Google & Meta Ads", "WhatsApp follow-up", "Conversion tracking", "Analytics & reporting"],
        "recommended_services": ["Website Development", "Google Ads", "Meta Ads", "Analytics & Reporting"],
        "benefits": ["More qualified leads", "More site visits", "Trackable campaign ROI"],
        "order": 8,
    },
    {
        "name": "Automotive", "slug": "automotive", "icon": "Car",
        "description": "Digital presence for dealerships, workshops and auto services.",
        "problem": "Vehicle owners search for services and dealers nearby, but many auto businesses are invisible online beyond a listing.",
        "solutions": ["Service / inventory website", "Booking & enquiry forms", "WhatsApp quotes", "Local SEO", "Google Ads for services", "Analytics"],
        "recommended_services": ["Website Development", "SEO & Local SEO", "Google Ads"],
        "benefits": ["More service bookings", "More walk-in enquiries", "Stronger local visibility"],
        "order": 9,
    },
    {
        "name": "Local Services", "slug": "local-services", "icon": "Wrench",
        "description": "Visibility and lead systems for local service professionals and SMBs.",
        "problem": "Great service businesses stay dependent on referrals because customers cannot find or contact them online.",
        "solutions": ["Professional website", "Lead & quote forms", "WhatsApp integration", "Google Business & local SEO", "Targeted local ads", "Analytics"],
        "recommended_services": ["Website Development", "SEO & Local SEO", "Google Ads"],
        "benefits": ["Steady enquiry flow", "Less referral dependence", "Measurable growth"],
        "order": 10,
    },
]

CASE_STUDIES = [
    {
        "title": "Local Gym Digital Growth", "slug": "local-gym-digital-growth", "industry": "Gyms & Fitness",
        "challenge": "A neighbourhood gym relied on walk-ins and referrals. People searching nearby could not find membership details or contact the gym easily.",
        "strategy": "Build a mobile-first website with membership plans, connect WhatsApp enquiries, and run local Google Ads during peak joining season.",
        "solution": "Conversion-focused website with plans, facilities gallery, trial-booking form and WhatsApp integration.",
        "marketing": "Local SEO on Google Business Profile plus search ads targeting 'gym near me' keywords in the area.",
        "tracking": "GA4, WhatsApp click tracking, call tracking and weekly lead reports.",
        "results": ["Demo outcome: steady flow of trial enquiries from search", "Demo outcome: measurable cost per lead from ads", "Demo outcome: membership decisions backed by weekly data"],
        "featured_image": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
        "isDemoProject": True, "featured": True, "published": True, "order": 1,
        "seo_title": "Demo Project: Local Gym Digital Growth | Dr Dukaan",
        "seo_description": "Demo case study showing how a local gym could grow memberships with a website, local SEO and Google Ads.",
    },
    {
        "title": "Retail Store E-Commerce Launch", "slug": "retail-store-ecommerce-launch", "industry": "Retail Stores",
        "challenge": "A retail store had strong walk-in sales but zero online presence and was losing younger customers to online competitors.",
        "strategy": "Launch a mobile-first online store with the full product catalogue and WhatsApp ordering for local delivery.",
        "solution": "E-commerce store with catalogue, cart, order management and WhatsApp order support.",
        "marketing": "Meta Ads showcasing bestsellers to local audiences plus Google visibility for product searches.",
        "tracking": "GA4 e-commerce events, order source tracking and monthly sales reports.",
        "results": ["Demo outcome: orders from customers beyond walking distance", "Demo outcome: repeat purchases through customer accounts", "Demo outcome: clear view of which products sell online"],
        "featured_image": "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
        "isDemoProject": True, "featured": True, "published": True, "order": 2,
        "seo_title": "Demo Project: Retail Store E-Commerce Launch | Dr Dukaan",
        "seo_description": "Demo case study showing how a retail store could launch an online store and grow sales beyond footfall.",
    },
    {
        "title": "Hospital Digital Presence", "slug": "hospital-digital-presence", "industry": "Hospitals & Clinics",
        "challenge": "A multi-speciality clinic had excellent doctors offline but an outdated website, no appointment enquiry flow and poor local search visibility.",
        "strategy": "Rebuild the website around specialities and doctors, add appointment enquiries, and optimize Google Business for local searches.",
        "solution": "Modern website with doctor profiles, speciality pages, appointment enquiry forms and WhatsApp for patient questions.",
        "marketing": "Local SEO for treatment and speciality keywords with monthly content updates.",
        "tracking": "GA4, enquiry tracking, call tracking and monthly performance reporting.",
        "results": ["Demo outcome: more appointment enquiries from search", "Demo outcome: higher patient trust from professional profiles", "Demo outcome: visibility into which specialities get searched most"],
        "featured_image": "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=1200&q=80",
        "isDemoProject": True, "featured": False, "published": True, "order": 3,
        "seo_title": "Demo Project: Hospital Digital Presence | Dr Dukaan",
        "seo_description": "Demo case study showing how a hospital could grow patient enquiries with a modern website and local SEO.",
    },
    {
        "title": "Wholesale Lead Generation", "slug": "wholesale-lead-generation", "industry": "Wholesale Businesses",
        "challenge": "A wholesale distributor depended entirely on existing buyers and trade references, with no way for new retailers to discover the catalogue.",
        "strategy": "Publish the full product catalogue online with a B2B enquiry system and capture leads through search visibility.",
        "solution": "Catalogue website with category pages, bulk enquiry forms and WhatsApp for order discussions.",
        "marketing": "SEO for product and category keywords plus targeted digital advertising to retailer audiences.",
        "tracking": "Lead source tracking, WhatsApp click tracking and monthly enquiry reports.",
        "results": ["Demo outcome: new B2B enquiries from outside the referral network", "Demo outcome: buyers self-educate on the catalogue before calling", "Demo outcome: enquiry data guides which categories to promote"],
        "featured_image": "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
        "isDemoProject": True, "featured": False, "published": True, "order": 4,
        "seo_title": "Demo Project: Wholesale Lead Generation | Dr Dukaan",
        "seo_description": "Demo case study showing how a wholesale business could generate B2B leads online with a catalogue and SEO.",
    },
]

TESTIMONIALS = [
    {"name": "Demo Client", "business": "Neighbourhood Fitness Centre", "role": "Owner", "photo": "", "rating": 5, "isDemo": True, "published": True, "order": 1,
     "testimonial": "DEMO TESTIMONIAL — This is sample placeholder text showing how a real client testimonial will appear once genuine client feedback is published."},
    {"name": "Demo Client", "business": "City Retail Store", "role": "Founder", "photo": "", "rating": 5, "isDemo": True, "published": True, "order": 2,
     "testimonial": "DEMO TESTIMONIAL — This is sample placeholder text showing how a real client testimonial will appear once genuine client feedback is published."},
    {"name": "Demo Client", "business": "Speciality Clinic", "role": "Director", "photo": "", "rating": 5, "isDemo": True, "published": True, "order": 3,
     "testimonial": "DEMO TESTIMONIAL — This is sample placeholder text showing how a real client testimonial will appear once genuine client feedback is published."},
]

PRICING_PLANS = [
    {
        "name": "Starter", "slug": "starter",
        "description": "For businesses starting their digital journey.",
        "price": "Get Quote", "billing_type": "One-time / Monthly options",
        "features": ["Professional website", "WhatsApp integration", "Google Business support", "Basic SEO", "GA4 setup", "Lead form", "Basic analytics"],
        "badge": "", "cta": "Get Quote", "highlighted": False, "visible": True, "order": 1,
    },
    {
        "name": "Growth", "slug": "growth",
        "description": "For businesses looking for more customers.",
        "price": "Get Quote", "billing_type": "Monthly growth partnership",
        "features": ["Advanced website", "SEO & Local SEO", "Google Ads", "Meta Ads", "Conversion tracking", "GA4 reporting", "Lead generation system", "Monthly reporting"],
        "badge": "Most Popular", "cta": "Get Quote", "highlighted": True, "visible": True, "order": 2,
    },
    {
        "name": "Scale", "slug": "scale",
        "description": "For businesses wanting a complete digital ecosystem.",
        "price": "Get Quote", "billing_type": "Custom engagement",
        "features": ["Website + Mobile App", "E-Commerce", "SEO & Local SEO", "Google Ads", "Meta Ads", "Analytics & attribution", "Lead system", "Monthly reporting", "Continuous optimization"],
        "badge": "", "cta": "Get Quote", "highlighted": False, "visible": True, "order": 3,
    },
]

FAQS = [
    {"question": "Do you work with businesses outside Hyderabad and Kurnool?", "answer": "Yes. Our teams are based in Hyderabad and Kurnool, but we serve businesses remotely across India. Most of our work happens over WhatsApp, calls and shared dashboards.", "order": 1, "visible": True},
    {"question": "Can you build an e-commerce website?", "answer": "Yes. We build online stores with product catalogues, order management, payments architecture and WhatsApp integration — designed for mobile-first shopping.", "order": 2, "visible": True},
    {"question": "Can you build mobile apps?", "answer": "Yes. We build custom Android and iOS apps for bookings, orders, memberships and customer engagement, designed around your business workflow.", "order": 3, "visible": True},
    {"question": "Do you manage Google Ads?", "answer": "Yes. We plan, launch and optimize Google Ads campaigns with proper conversion tracking so you know exactly what your ad spend brings back.", "order": 4, "visible": True},
    {"question": "Do you manage Meta Ads?", "answer": "Yes. We run Facebook and Instagram campaigns focused on leads, enquiries and sales, with audience targeting, creative testing and remarketing.", "order": 5, "visible": True},
    {"question": "Do you provide SEO?", "answer": "Yes. We provide technical SEO, on-page SEO, local SEO and Google Business optimization so more customers find you when they search.", "order": 6, "visible": True},
    {"question": "Do you provide monthly reporting?", "answer": "Yes. Growth and Scale engagements include clear monthly reports covering traffic, leads, campaign performance and what we recommend next.", "order": 7, "visible": True},
    {"question": "Can you set up Google Analytics 4?", "answer": "Yes. GA4 setup is included in applicable packages. We track visitors, traffic sources, conversions, CTA clicks, WhatsApp clicks and lead submissions.", "order": 8, "visible": True},
    {"question": "Can I update my website later?", "answer": "Yes. Your website is built so content can be updated easily, and our team can handle changes for you as part of ongoing support.", "order": 9, "visible": True},
    {"question": "How long does a website take?", "answer": "Most business websites go live in two to four weeks depending on content and features. We share a clear timeline before starting.", "order": 10, "visible": True},
    {"question": "Do you provide ongoing support?", "answer": "Yes. We offer ongoing support and growth partnerships covering updates, campaigns, reporting and continuous improvement.", "order": 11, "visible": True},
    {"question": "Can I start with only a website?", "answer": "Absolutely. Many clients start with a website and add marketing, ads and analytics as they grow. We will recommend what fits your stage and budget.", "order": 12, "visible": True},
    {"question": "Do you work with small businesses?", "answer": "Yes. Local and small businesses are exactly who we built Dr Dukaan for. Our packages are designed to be practical for growing businesses.", "order": 13, "visible": True},
]

BLOG_POSTS = [
    {
        "title": "Why Your Local Business Needs More Than a Website", "slug": "why-local-business-needs-more-than-website",
        "excerpt": "A website alone does not bring customers. Here is how a complete digital growth system turns online presence into enquiries and sales.",
        "content": "Many local businesses get a website built and then wait for customers to arrive. They rarely do — because a website without visibility is like a shop on a street nobody walks down.\n\nA digital growth system connects the pieces: a fast website, Google visibility, WhatsApp for instant contact, advertising to reach the right people, and analytics to show what is working.\n\nStart with the foundation (website + Google Business Profile + WhatsApp), then layer on SEO and ads as you grow. Measure everything, and let the data guide your next move.\n\nThat is the system we build for every business we work with.",
        "featured_image": "https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "category": "Digital Growth", "author": "Dr Dukaan Team", "published": True,
        "seo_title": "Why Your Local Business Needs More Than a Website | Dr Dukaan",
        "seo_description": "A website alone does not bring customers. Learn how a complete digital growth system turns presence into enquiries.",
    },
    {
        "title": "Google Ads vs Meta Ads: What Should a Local Business Choose?", "slug": "google-ads-vs-meta-ads-local-business",
        "excerpt": "Both platforms can grow your business — but they work differently. A simple guide for local business owners.",
        "content": "Google Ads captures demand: people already searching for what you sell. Meta Ads creates demand: reaching people who match your ideal customer while they browse.\n\nIf customers actively search for your service (a dentist, a gym, a wholesaler), Google Ads usually delivers faster, more direct enquiries. If your product benefits from visual discovery (fashion, food, salons), Meta Ads can be powerful.\n\nMost growing businesses use both, with proper conversion tracking so every rupee is accountable. Start with one, measure, then expand.",
        "featured_image": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=srgb&fm=jpg&q=85&w=940",
        "category": "Advertising", "author": "Dr Dukaan Team", "published": True,
        "seo_title": "Google Ads vs Meta Ads for Local Businesses | Dr Dukaan",
        "seo_description": "A simple guide for local business owners on choosing between Google Ads and Meta Ads.",
    },
]

SETTINGS = {
    "website": {
        "brand_name": "Dr Dukaan",
        "tagline": "Digital Growth Partner for Local Businesses.",
        "hero_eyebrow": "Digital Growth Partner for Local Businesses",
        "hero_title_1": "Take Your Local Business",
        "hero_title_2": "From Offline to",
        "hero_title_accent": "Online.",
        "hero_subtitle": "We build the digital systems, marketing and growth strategy that help local businesses attract more customers.",
        "growth_statement": "Build. Launch. Market. Measure. Grow.",
        "hero_primary_cta": "Get a Free Digital Growth Consultation",
        "hero_secondary_cta": "Chat on WhatsApp",
        "hero_tertiary_cta": "Explore Our Services",
        "differentiator_title": "We Don't Just Build Your Website.",
        "differentiator_statement": "WE BUILD YOUR DIGITAL GROWTH SYSTEM.",
        "differentiator_copy": "Launching a website is only the beginning. We help you build the complete digital system around your business and continuously improve it.",
        "final_cta_title_1": "Your Business Is Already Growing Offline.",
        "final_cta_title_2": "Let's Make It Grow Online.",
        "final_cta_subtitle": "Tell us where your business is today. We'll help you identify the digital opportunities that can move it forward.",
        "footer_tagline": "Digital Growth Partner for Local Businesses.",
    },
    "whatsapp": {
        "number": "919985510295",
        "display": "+91 9985510295",
        "default_message": "Hi Dr Dukaan, I want to grow my business online. I'd like to discuss your digital growth options.",
        "hero_message": "Hi Dr Dukaan, I want to take my business online and would like to discuss a digital growth solution.",
        "quote_message": "Hi Dr Dukaan, I'd like to get a quote for my business. Please share the details.",
    },
    "contact": {
        "email": "drdukaan@gmail.com",
        "locations": ["Hyderabad, Telangana", "Kurnool, Andhra Pradesh"],
        "service_area": "Serving businesses remotely across India.",
        "business_hours": "Mon–Sat, 10:00 AM – 7:00 PM IST",
        "google_maps_url": "",
        "social": {"instagram": "", "facebook": "", "linkedin": "", "twitter": "", "youtube": ""},
    },
    "seo": {
        "home_title": "Dr Dukaan — Digital Growth Partner for Local Businesses",
        "home_description": "We take local businesses online and help them grow with websites, apps, e-commerce, SEO, Google Ads, Meta Ads and analytics. Hyderabad & Kurnool, serving India.",
        "og_title": "Dr Dukaan — Take Your Local Business From Offline to Online",
        "og_description": "Build. Launch. Market. Measure. Grow. One digital partner for websites, marketing and growth.",
        "og_image": "",
        "keywords": "digital marketing Hyderabad, website development Kurnool, local business SEO, Google Ads agency India, e-commerce development",
    },
    "analytics": {
        "ga4_id": "",
        "track_page_views": True,
        "track_cta_clicks": True,
        "track_whatsapp_clicks": True,
        "track_form_submissions": True,
    },
}
